# Generated by Django 3.0 on 2022-11-29 19:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0003_auto_20221129_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='rewiew',
            new_name='review',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('author', 'review')},
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('author', 'review'), name='unique_author_comment'),
        ),
    ]
