# Generated by Django 3.0 on 2022-11-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20221129_2231'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_author_comment',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
